{{- if .Values.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dcgm-extras-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fake-dcgm-extras.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "fake-dcgm-extras.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fake-dcgm-extras.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: dcgm-extras-exporter
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --listen=:{{ .Values.service.port }}
            - --gpus-per-node={{ .Values.gpusPerNode }}
            - --product-name={{ .Values.productName }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - name: dcgm-metrics
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: dcgm-metrics
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: dcgm-metrics
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
{{- end }}
